/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/assets/revolver.glb 
*/

import React from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { editable as e } from "@theatre/r3f";
import { useFrame } from "@react-three/fiber";
import { demoSheet } from "./Sheet";

export function Revolver(props) {
  const { nodes, materials } = useGLTF("/assets/revolver.glb");

  const scroll = useScroll();

  useFrame(() => {
    demoSheet.sequence.position = scroll.offset * 7;
  });

  return (
    <group {...props} dispose={null}>
      <e.group
        position={[0, 22.02, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.002}
        theatreKey="revolver"
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <e.mesh
            theatreKey="arbor"
            geometry={nodes.Arbor_LP_Mat_Set2Combined_0.geometry}
            material={materials["Mat_Set2Combined.001"]}
            position={[945.379, -37.134, 0.066]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="backStrapGuardScrew1"
            geometry={
              nodes.BackStrap_GuardScrew1_LP_Mat_Set1Combined_0.geometry
            }
            material={materials["Mat_Set1Combined.001"]}
            position={[660.168, 262.655, 33.739]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="backStrapGuardScrew2"
            geometry={
              nodes.BackStrap_GuardScrew2_LP_Mat_Set1Combined_0.geometry
            }
            material={materials["Mat_Set1Combined.001"]}
            position={[660.213, 262.599, -33.523]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="backStrapGuardScrew3"
            geometry={
              nodes.BackStrap_GuardScrew3_LP_Mat_Set1Combined_0.geometry
            }
            material={materials["Mat_Set1Combined.001"]}
            position={[820.232, -191.43, 0.073]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="ballShot"
            geometry={nodes.BallShot_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[303.389, 274.904, 0.064]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="barrel"
            geometry={nodes.Barrel_LP_Mat_Set3Combined_0.geometry}
            material={materials["Mat_Set3Combined.001"]}
            position={[-622.939, 339.747, 0.022]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="bolt"
            geometry={nodes.Bolt_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[478.674, 228.5, -7.247]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="boltScrew"
            geometry={nodes.BoltScrew_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[528.945, 202.364, -32.485]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.group theatreKey="caps">
            <mesh
              theatreKey="cap1"
              geometry={nodes.Cap1_LP_Mat_Set1Combined_0.geometry}
              material={materials["Mat_Set1Combined.001"]}
              position={[538.686, 417.258, 0.069]}
              rotation={[2.618, 0, 0]}
              scale={100}
            />
            <mesh
              theatreKey="cap2"
              geometry={nodes.Cap2_LP_Mat_Set1Combined_0.geometry}
              material={materials["Mat_Set1Combined.001"]}
              position={[538.686, 381.67, -61.572]}
              rotation={[2.618, 0, 0]}
              scale={100}
            />
            <mesh
              theatreKey="cap3"
              geometry={nodes.Cap3_LP_Mat_Set1Combined_0.geometry}
              material={materials["Mat_Set1Combined.001"]}
              position={[538.686, 310.493, -61.572]}
              rotation={[2.618, 0, 0]}
              scale={100}
            />
            <mesh
              theatreKey="cap4"
              geometry={nodes.Cap4_LP_Mat_Set1Combined_0.geometry}
              material={materials["Mat_Set1Combined.001"]}
              position={[538.686, 274.904, 0.069]}
              rotation={[2.618, 0, 0]}
              scale={100}
            />
            <mesh
              theatreKey="cap5"
              geometry={nodes.Cap5_LP_Mat_Set1Combined_0.geometry}
              material={materials["Mat_Set1Combined.001"]}
              position={[538.686, 310.493, 61.71]}
              rotation={[2.618, 0, 0]}
              scale={100}
            />
            <mesh
              theatreKey="cap6"
              geometry={nodes.Cap6_LP_Mat_Set1Combined_0.geometry}
              material={materials["Mat_Set1Combined.001"]}
              position={[538.686, 381.67, 61.71]}
              rotation={[2.618, 0, 0]}
              scale={100}
            />
          </e.group>
          <e.mesh
            theatreKey="cylinder"
            geometry={nodes.Cylinder_LP_Mat_Set3Combined_0.geometry}
            material={materials["Mat_Set3Combined.001"]}
            position={[-622.939, 339.747, 0.022]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="frame"
            geometry={nodes.Frame_LP_Mat_Set2Combined_0.geometry}
            material={materials["Mat_Set2Combined.001"]}
            position={[945.379, -37.134, 0.066]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="grip"
            geometry={nodes.Grip_LP_Mat_Set2Combined_0.geometry}
            material={materials["Mat_Set2Combined.001"]}
            position={[888.938, 1.49, 0.066]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="hammer"
            geometry={nodes.Hammer_LP_Mat_Set2Combined_0.geometry}
            material={materials["Mat_Set2Combined.001"]}
            position={[945.379, -37.134, 0.066]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="hammerScrew"
            geometry={nodes.HammerScrew_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[647.685, 229.189, 10.422]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="hand"
            geometry={nodes.Hand_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[606.62, 230.067, 27.099]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="handSpring"
            geometry={nodes.HandSpring_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[621.919, 286.53, 34.117]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="LLLatchPin"
            geometry={nodes.LLLatchPin_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[-622.948, 336.883, 0.063]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="LLLatchSpring"
            geometry={nodes.LLLatchSpring_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[-512.951, 336.93, 0.188]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="loadingLeverLatch"
            geometry={nodes.LoadingLever_LP_Mat_Set3Combined_0.geometry}
            material={materials["Mat_Set3Combined.001"]}
            position={[-622.939, 339.747, 0.022]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="loadingLeverLatch"
            geometry={nodes.LoadingLeverLatch_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[-570.289, 336.932, 0.063]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="loadingPlunger"
            geometry={nodes.LoadingPlunger_LP_Mat_Set3Combined_0.geometry}
            material={materials["Mat_Set3Combined.001"]}
            position={[-622.939, 339.747, 0.022]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="mainSpring"
            geometry={nodes.MainSpring_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[789.847, 23.666, 0.067]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="mainSpringScrew"
            geometry={nodes.MainSpringScrew_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[845.893, -163.315, -0.102]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="MajorLoadingLeverScrew"
            geometry={
              nodes.MajorLoadingLeverScrew_LP_Mat_Set1Combined_0.geometry
            }
            material={materials["Mat_Set1Combined.001"]}
            position={[51.187, 343.246, 17.54]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="MinorLoadingLeverScrew"
            geometry={
              nodes.MinorLoadingLeverScrew_LP_Mat_Set1Combined_0.geometry
            }
            material={materials["Mat_Set1Combined.001"]}
            position={[-17.171, 274.355, 2.438]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.group theatreKey="nipples">
            <mesh
              geometry={nodes.Nipple1_LP_Mat_Set1Combined_0.geometry}
              material={materials["Mat_Set1Combined.001"]}
              position={[489.888, 417.972, 0.047]}
              rotation={[2.618, 0, 0]}
              scale={100}
            />
            <mesh
              geometry={nodes.Nipple2_LP_Mat_Set1Combined_0.geometry}
              material={materials["Mat_Set1Combined.001"]}
              position={[489.888, 382.007, -62.2]}
              rotation={[2.618, 0, 0]}
              scale={100}
            />
            <mesh
              geometry={nodes.Nipple3_LP_Mat_Set1Combined_0.geometry}
              material={materials["Mat_Set1Combined.001"]}
              position={[489.888, 310.117, -62.177]}
              rotation={[2.618, 0, 0]}
              scale={100}
            />
            <mesh
              geometry={nodes.Nipple4_LP_Mat_Set1Combined_0.geometry}
              material={materials["Mat_Set1Combined.001"]}
              position={[489.888, 274.192, 0.092]}
              rotation={[2.618, 0, 0]}
              scale={100}
            />
            <mesh
              geometry={nodes.Nipple5_LP_Mat_Set1Combined_0.geometry}
              material={materials["Mat_Set1Combined.001"]}
              position={[489.888, 310.157, 62.339]}
              rotation={[2.618, 0, 0]}
              scale={100}
            />
            <mesh
              geometry={nodes.Nipple6_LP_Mat_Set1Combined_0.geometry}
              material={materials["Mat_Set1Combined.001"]}
              position={[489.888, 382.047, 62.316]}
              rotation={[2.618, 0, 0]}
              scale={100}
            />
          </e.group>
          <e.mesh
            theatreKey="roller"
            geometry={nodes.Roller_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[704.885, 220.941, 0.109]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="rollerPin"
            geometry={nodes.RollerPin_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[704.886, 220.941, 0.109]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="tang"
            geometry={nodes.Tang_LP_Mat_Set2Combined_0.geometry}
            material={materials["Mat_Set2Combined.001"]}
            position={[945.379, -37.134, 0.066]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="triggerBoltSpring"
            geometry={nodes.Trigger_BoltSpring_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[459.336, 196.399, -0.4]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="triggerBoltSpringScrew"
            geometry={
              nodes.Trigger_BoltSpringScrew_LP_Mat_Set1Combined_0.geometry
            }
            material={materials["Mat_Set1Combined.001"]}
            position={[420.867, 204.73, 0.182]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="trigger"
            geometry={nodes.Trigger_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[563.212, 146.45, 8.809]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="triggerGuard"
            geometry={nodes.TriggerGuard_LP_Mat_Set2Combined_0.geometry}
            material={materials["Mat_Set2Combined.001"]}
            position={[945.379, -37.134, 0.066]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="triggerGuardScrew1"
            geometry={nodes.TriggerGuardScrew1_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[661.129, 154.166, 34.035]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="triggerGuardScrew2"
            geometry={nodes.TriggerGuardScrew2_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[661.111, 154.167, -33.917]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="triggerGuardScrew3"
            geometry={nodes.TriggerGuardScrew3_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[343.006, 207.942, 0.088]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="triggerScrew"
            geometry={nodes.TriggerScrew_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[563.985, 185.913, -32.44]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="Wedge"
            geometry={nodes.Wedge_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[183.911, 342.73, -24.332]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="WedgePin"
            geometry={nodes.WedgePin_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[183.912, 347.713, -46.051]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="WedgeScrew"
            geometry={nodes.WedgeScrew_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[183.832, 366.359, -42.816]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
          <e.mesh
            theatreKey="WedgeSpring"
            geometry={nodes.WedgeSpring_LP_Mat_Set1Combined_0.geometry}
            material={materials["Mat_Set1Combined.001"]}
            position={[183.887, 350.74, -15.239]}
            rotation={[2.618, 0, 0]}
            scale={100}
          />
        </group>
      </e.group>
    </group>
  );
}

useGLTF.preload("/assets/revolver.glb");
